version: '3'
services:
  script:
    build:
      context: .
      dockerfile: Dockerfile
    image: walmart-scraper
    command: "python3 crawl.py 'https://www.walmart.ca/search?q=cerave&c=6000198722778'"
    volumes:
      - .:/app